### ISSUE TITLE
Increase size of path images

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop#10]
This issue may be related to #9, but I think users would benefit from an increase in the size of the path images, even if that means reducing the size of the font (eg, "Answer 1 of 1000").  - KF

**Comment by patrickkwang** [comment]
Just to clarify, you mean the path visualization in the middle of the answers page?
![image](https://user-images.githubusercontent.com/1263870/36263773-f0391618-1238-11e8-84c9-1ba46cb0249e.png)

**Comment by karafecho** [comment]
Yes, I think it would be helpful to increase the size (primarily font size) of all visualizations (paths, construction graph), except (maybe) the interactive blackboard.

**Comment by kennethmorton** [comment]
Hopefully this is solved after layout changes. Graph has more pixels now and hopefully things are better.
