### ISSUE TITLE
Incorporate Enrichment

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#103]
One aspect to a workflow might be an enrichment either in genes, or functions, or something else.  For instance, given a set of genes, find the functions of those genes that are overrepresented compared to chance.  

This could be done two ways: either explicitly as an enrichment operation or as something to incorporate into ranking.

**Comment by patrickkwang** [comment]
Kenny and I have been discussing an extension to our machine question formulation that may be a partial answer to this. It allows answers to contain sets of parallel nodes (of arbitrary size). Then we hope ranking can incorporate something of this "enrichment" idea.
