### ISSUE TITLE
Pattern Questions - backend

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#115]
Our current queries are linear with fixed nodes at the ends.  We want to allow arbitrary pattern questions, with fixed nodes at arbitrary locations.  I can think of two ways to do this.

1) Decompose the question into a series of linear queries with fixed nodes at the ends and run them as we run things now, then stuff gets stitched together in the database.  The downside here is really on the support edges.

2) Extend the current approach to take in a pattern, compose the cypher, and run program.  Note that while it seems simpler to handle support edges here, it's not that simple because the support edge code also assumes linear paths...

**Comment by patrickkwang** [comment]
Done. We took the second approach, and aren't worried about support anymore because it's moved to the ranking stage.
