### ISSUE TITLE
Time- and user-stamp blackboards

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop#12]
This feature may be related to #5, but it is important for users to be able to determine who created a blackboard and when.  - KF

**Comment by patrickkwang** [comment]
The plan, according to our re-imagining of reasoner concepts, is to have Questions, which are user-owned (for editing/deleting), and Answers, which are time-stamped and associated with specific Questions. Questions are independent of the Knowledge Graph and therefore need no time-stamping.

**Comment by karafecho** [comment]
Makes sense to me.
