### ISSUE TITLE
Blacklist Nodes

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#125]
Highly connected nodes lead to a combinatorial explosion, which slows down building, supporting, and ranking.   For the most part, these nodes are completely uninteresting.  For instance, "multicellular organism" from uberon is a catchall - it contains every kind of cell and is affected by every phenotype. So it ends up connecting everything to everything, but in the most useless way possible.

Removing that node from an AOP reduces the number of edges that need to be checked for support from about 700k to about 80k, almost a factor of 10.

How do we want to handle filtering this kind of node in general?  I can think of a few options:

1) Define a list of nodes a priori that are like this by looking at each ontology and deciding whether the top-level terms are useful or not.  This smacks of thresholding and its associated problems, but it's also pragmatic.

2) Re-actively decide which nodes are garbage: start with a given filter list, run many queries over time.  Each time results are ranked, note which nodes appear in good results.  If a node never appears in a good path, then it may be a node that we want to add to the filter.

3) Threshold on node connectivity: if a node is connected to a significant fraction of the universe then it's probably not specific enough to be useful.  This can be done in an automated way, which is both good and bad.

**Comment by patrickkwang** [comment]
3 sounds like the most principled way to go about this, but I worry about implementation. When we get a node like this, we make a KS call or two and keep/delete it based on the results?

I'm not sure that 2 will do what we want.

I think 1 is the way to go right now. It's relatively easy, and we can shift to another solution like 3 later.

**Comment by cbizon** [comment]
We do blacklist nodes now...
