### ISSUE TITLE
CTD API returning extra rows

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#128]
The following call should return chemicals that interact with Gene 43 (ACHE).

It does, but it also returns many other rows with other genes.  It looks like it's returning any gene that ends in 43 (like 5243).

curl -X GET --header 'Accept: application/json' 'https://ctdapi.renci.org/CTD_chem_gene_ixns_GeneID/43/'

**Comment by ColinKCurtis** [comment]
There are now two updated variants for the above type of call to the CTDAPI:

1) (default setting) If you want a 'strict', exclusive set of returned values which match your input exactly:

curl -X GET --header 'Accept: application/json' 'https://ctdapi.renci.org/CTD_chem_gene_ixns_GeneID/43/?regex=false'

2) OR, if you would like a 'permissive', inclusive set such that any string, in the relevant field being searched, which contains your input is returned:

curl -X GET --header 'Accept: application/json' 'https://ctdapi.renci.org/CTD_chem_gene_ixns_GeneID/43/?regex=true'

This change has been applied to all of the CTD API endpoints, not just GeneID! Any calls to CTD API will have to be updated to include this '/?regex=true' or '/?regex=false' flag at the end!

**Comment by cbizon** [comment]
Can the call default to regex=false?

**Comment by ColinKCurtis** [comment]
regex=false is currently the default, yes

**Comment by cbizon** [comment]
So I don't understand what this means: 

> Any calls to CTD API will have to be updated to include this '/?regex=true' or '/?regex=false' flag at the end!

If there's a default, then I don't need to include this (assuming I'm ok with false), right?

**Comment by ColinKCurtis** [comment]
In the current implementation, those endings must be specified, '/regex=?true' or /regex=?false'. 

Should I make the old call style (omitting the '?regex=XXXX' portion) work again and default to the '?regex=false' condition?

**Comment by ColinKCurtis** [comment]
ctdapi has been updated to accept the following three styles of curl command:

1) curl -X GET --header 'Accept: application/json' 'https://ctdapi.renci.org/CTD_chem_gene_ixns_GeneID/43/'

2) curl -X GET --header 'Accept: application/json' 'https://ctdapi.renci.org/CTD_chem_gene_ixns_GeneID/43/?include_similar=false'

3) curl -X GET --header 'Accept: application/json' 'https://ctdapi.renci.org/CTD_chem_gene_ixns_GeneID/43/'include_similar=true'

1 and 2 return identical results, which exclude values merely similar to the input (in this case '43')
3 returns a larger set of results than 1 and 2, including values which are similar to the input
