### ISSUE TITLE
Remove auto-population of new blackboard names

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop#13]
The blackboard name for the blackboard types is automatically populated as “Question 1 Example” or “Question 2 Example” when one clicks on the example buttons. This makes it easy to forget to name the new blackboard and instead end up with the default names. Also see #11. - KF

**Comment by patrickkwang** [comment]
We did not originally expect these examples to be used as templates for general question generation. If we want a set of common templates (instead of or in addition to complete examples), we can force the user to set the name.
