### ISSUE TITLE
Graph Template "Analyze"

### ISSUE THREAD

**Issue by kennethmorton** [NCATS-Gamma/robokop#130]
The NLP engine does some bionames searches and things based on the natural language input. With the new editor it is possible for the user to things they intend to be search terms. It would be nice if we had a similar method to do the bionames look ups from a JSON graph template rather than exclusively natural language. 

We need another API end point for this, probably in the NLP area.

**Comment by patrickkwang** [comment]
@kennethmorton I'm not entirely sure what this means. Is it done with the latest question editor?

**Comment by kennethmorton** [comment]
I think this is mostly OBE. The term new used above is relative to 2018. Let's close it.
