### ISSUE TITLE
test_cell_to_anatomy verbosity

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Gamma/robokop#131]
uberon.get_anatomy_by_cell() for mast cell (CL:0000097) returns:
- anatomical entity (UBERON:0001062)
- material anatomical entity (UBERON:0000465)
- anatomical structure (UBERON:0000061)
- multicellular anatomical structure (UBERON:0010000)
- anatomical system (UBERON:0000467)
- multicellular organism (UBERON:0000468)
- immune system (UBERON:0002405)

I think the test expected immune system alone. Has the service changed? Should the test change?

**Comment by cbizon** [comment]
The service had changed to allow these parent classes, and now the test reflects that.
