### ISSUE TITLE
ctd.gene_to_drug() returns duplicate results

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Gamma/robokop#133]
test_gene_to_drug_unique() and test_gene_to_drug_ACHE() fail.

**Comment by cbizon** [comment]
We get back predicates from services, and try to translate them into something from the biolink model.  Currently biolink doesn't have enough relationships for us to capture most of the information from CTD predicates.  So several of the original predicates would get lost if we just uniqued on standard predicates. So for the moment we're uniqueing on the original predicate.  This gives us non-unique standard predicates, which is what the tests are complaining about.

I've changed the tests to check for original_predicate uniqueness, and so they currently pass, but the right solution is to have a richer set of chemical predicates in the biolink model, which I'm talking about with Matt.  So leaving the issue open as a reminder.
