### ISSUE TITLE
Deleting a question while ROBOKOP is updating the KG

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop#134]
I think it might be useful to allow users to delete a question while ROBOKOP is updating the KG.

**Comment by patrickkwang** [comment]
Do you mean cancel the update and then delete the question, or delete it while the update process completes?

**Comment by karafecho** [comment]
I think I mean delete the question while the update process completes. Others may disagree, but the update seems to get stuck once in a while, or maybe it's just really, really slow. For example, this question:  Metformin -> gene -> biological_process_or_molecular_activity -> cell -> anatomical_entity -> Nausea.

**Comment by patrickkwang** [comment]
Updating is definitely slow, for a variety of reasons. But why might one want to delete the question while this is happening? Then you'll have no question, but the cached knowledge graph will be updated, slowly.

**Comment by karafecho** [comment]
I think one might want to delete the question for the same reason one might want to delete any question, it's just that right now, a user cannot delete a question while the KG is updating.
