### ISSUE TITLE
Auto-reply email link for new answers

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop#144]
The auto-reply email link for new answers appears to be broken.

----- Forwarded Message -----
From: "no-reply@mailer.robokop.org" <no-reply@mailer.robokop.org>
To: kfecho@copperlineprofessionalsolutions.com 
Sent: Thursday, August 30, 2018 2:19 PM
Subject: ROBOKOP: Answers Ready

We have finished answering your question: "".
ANSWERS

![image](https://user-images.githubusercontent.com/26254388/44885056-dabcb800-ac8c-11e8-99dc-1bb22e2b5c5a.png)

**Comment by patrickkwang** [comment]
We just have to set ROBOKOP_HOST to the public url of the robokop instance. These emails are practically the only thing that it impacts. This is now fixed on robokop.renci.org.
