### ISSUE TITLE
"I Like This Answer" options

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop#15]
Re “I Like This Answer”: perhaps include additional options that take into account the fact that users may be intrigued, but uncertain about certain answers. For example, “I Like This Answer”, “I Am Intrigued By This Answer”, “I Would Like A Second Opinion Regarding This Answer”, “This Answer Makes No Sense To Me”. - KF

**Comment by kennethmorton** [comment]
In the interest of the coming backend and UI overhaul, we decided to think more deeply about this. Under the hood we will store the following quantities for each instance of provided feedback

* **correct** - categorical with the following dimensions: 
  * definitely incorrect, i dont think so, maybe, probably correct, definitely correct
* **interest** - 0-5 star rating
* **notes** - Free text for the user to type what they want

The UI for correctness and interest is TBD but I think this will reduce the ambiguity of what "like" means and cover the basis of wanting a second opinion (or how much we can trust this for future machine learning).

Thoughts?
