### ISSUE TITLE
Answer Set Exporting

### ISSUE THREAD

**Issue by kennethmorton** [NCATS-Gamma/robokop#154]
We require a specification and code to transform an answer set (in standard format) to a different form. This has three main uses

* Machine Answer to Natural Answer - With a future NLP system we want to know how to transform something to a simple readable answer.
* To overhaul the Robokop Flowbokop service for greater flexibility
* To ease implementing other Reasoner teams modules into Flowbokop

The hardest part as I see it is defining a language for operations that work on the graph. This is not too unlike some of the functionality that Steve had implemented in his initial workflow implementation. 

Initial thoughts:

1. Method
    * Single Answer - A function will be applied to a single (top?) answer graph
    * Multiple Answer - A function will be applied to all (or a number of the top) answer graphs
2. Function
    * Edges or Nodes - Is the ultimate answer a function of the edges or nodes? - Usually nodes
    * Select - A filter operation for the nodes or edges
    * Operation - List, Count etc. Generally people want list.

The main question mark for me is a way to specify and perform the select over nodes/edges.

**Comment by cbizon** [comment]
I think this is solved?  Reopen if incorrect.
