### ISSUE TITLE
Exporting results

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop#16]
Would be nice to have a way to export select results (e.g., answer summaries, construction path). - KF

**Comment by kennethmorton** [comment]
Morphing this into a need identified at the May Hackathon.

We currently allow you to download the answer set in the standard format, but CSV or easily readable JSON would be much easier to work with when you reach the limits of ROBOKOP and want to use output from ROBOKOP in another service.

We need to have methods to define how things are exported from an answer and methods for the manager and UI to allow the user to define and call those.

**Comment by patrickkwang** [comment]
@kennethmorton, this seems resolved to me, but I'll leave it to you to close it.

**Comment by kennethmorton** [comment]
Maybe, you can download a giant answerset file, but I'm not sure that is the original intent. I think the goal was to get something digestible. I am going to hijack the issue to now be:

1. Make answer specific pages
2. Make an answer specific download
