### ISSUE TITLE
Need a way to determine list of available predicates for a question given the 2 node types and direction of the edge

### ISSUE THREAD

**Issue by sudeepmandal** [NCATS-Gamma/robokop#171]
This will be handy to have so we can provide a drop-down like selector for predicates in the machine question editor (when it is built out). It could be an internal API end point where someone POSTs the `node_from_type` and `node_to_type` and receives a list of strings with predicates that are available for that pairing of node types.

**Comment by cbizon** [comment]
Is the current service a solution to this?
