### ISSUE TITLE
Workflow 3: opposites

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#181]
Workflow 3 has the concept of opposing phenotypes.   In this case, we might have a phenotype like 'increased X' and we want to find 'decreased X'.  There are some logical definitions of terms that might help, but they are not fully populated.   The HPO authors have put together a list of opposite terms: 

https://github.com/Phenomics/phenopposites/blob/master/opposites/antonyms_HP.txt

but they are not part of the ontology itself.  

Should onto expose these?  If not, how do we get them?

**Comment by cbizon** [comment]
I don't think that these are inherent in ubergraph, but it might be the best place to compute/stash them?

**Comment by ColinKCurtis** [comment]
Jim moved ubergraph to https://github.com/NCATS-Tangerine/ubergraph
Colin added a bit of code to Makefile in order to collect the 'antonyms_HP.txt' file and reformat it for insertion to reasoner.renci.org/ontology

**Comment by cbizon** [comment]
These edges are now exposed in uberongraph with predicate RO:0002604
