### ISSUE TITLE
PMIDs from ctd display incorrectly

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#182]
![image](https://user-images.githubusercontent.com/10744350/47028281-14f7f100-d137-11e8-8b62-153b847a8a72.png)

Presumably this is actually a problem with the way CTD pubmed edges are written to neo4j?

**Comment by kennethmorton** [comment]
Sometimes PMIDs come through in as either

1. PMID:######
2. PUBMED:####### (I think this still might happen sometimes)
3. ########
4. PMID:#####|#####|#####|#####

Previously we only handled cases 1 and 2. Also handling case 3 in the UI is easy enough. That's the source of the bug shown above. While digging around I found case 4.

This is more difficult to fix in the UI and I believe is also being interpreted wrong in the ranker. I think this will look like one publication. 

I have observed this for  "ctd.gene_to_drug(CHEBI:34873-(increases_expression_of)->HGNC:1131)" but it could happen in other cases that I haven't seen.


<img width="908" alt="screen shot2" src="https://user-images.githubusercontent.com/1233522/47103358-172c7f00-d20d-11e8-85db-cdf8c956543b.png">

**Comment by cbizon** [comment]
Do you have examples of 2 or 3?    I can see how 4 could get past the (minimal) validation, bu if 2 or 3 are still occurring, then it may mean that something needs cleaned out of redis, or something more unusual.

**Comment by cbizon** [comment]
Pushed a fix for 4 and some improved validation of PMID formats

**Comment by kennethmorton** [comment]
Examples of 1, 3 and 4 are [here](http://robokop.renci.org/api/a/bwT9q9PgEcL9_1455/).


I haven't seen 2 in a while and it won't hurt the ranker or the UI so let's just forget about that one.

**Comment by cbizon** [comment]
What still remains is to rebuild neo4j and redis using the new CTD edges.

**Comment by cbizon** [comment]
The old CTD edges have been removed, which is technically enough to satisify this.  The new edges are being added now.
