### ISSUE TITLE
More info in "established using"

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#184]
![image](https://user-images.githubusercontent.com/10744350/47028578-a5cecc80-d137-11e8-8d51-98be773b8701.png)

There are two edges here because CTD.chemical_to_gene gives an edge and CTD.exposure_to_gene gives an edge.  established using should show this distinction.

**Comment by kennethmorton** [comment]
Fixed in the latest ui changes to be deployed soon.
