### ISSUE TITLE
Question Submission API

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#185]
We can run robokop using the APIs but the questions/answers don't show up in the UI.  It would be nice to be able to script up running many e.g. COPs and have the answers show up in the UI for perusal.

**Comment by kennethmorton** [comment]
This is supported through the manager API. Async mode is required where storage and display in the UI is the default. Directly using builder or ranker API bypasses storage and display in the UI.

**Comment by cbizon** [comment]
Great!
