### ISSUE TITLE
Self Omnicorp Edges

### ISSUE THREAD

**Issue by kennethmorton** [NCATS-Gamma/robokop#186]
Sometimes I see self edges omnicorp edges in the UI. We display them correctly but.. that's weird right? Why are they there? Is there some bug in the ranker somewhere?

<img width="907" alt="screenshot" src="https://user-images.githubusercontent.com/1233522/47102783-9c169900-d20b-11e8-9971-d631dd457b82.png">

**Comment by cbizon** [comment]
What happens here is that the question is (disease)-(chemical)-(gene)-(chemical), and we've specified predicates. But it's possible that chemical1 and chemical2 are the same, as in the picture above.

In this case, we should probably either filter these answers out out or keep them but not look for self-self omnicorp edges, (which can never be significant compared to background).

**Comment by kennethmorton** [comment]
Got it. So we don't display the self edges in the UI anymore. This can also cause some issues with repeated support edges. After some tweaking how we display edges in the graph you might see this.

<img width="415" alt="screen shot 2018-10-18 at 2 57 25 pm" src="https://user-images.githubusercontent.com/1233522/47177359-377c3c80-d2e6-11e8-9a61-7a48eed8cf7c.png">

For the time being we are going to live with this.
