### ISSUE TITLE
Remove arrowhead from undirected edge

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#188]
In the UI, every edge is directed, and this gets passed forward into the ranker cypher query.  But sometimes we don't know the direction of the edge that we want, especially if we don't know the list of possible predicates.  So it would be good to allow for non-directed edges.

Related issues:
#165 #171

**Comment by cbizon** [comment]
Patrick points out how this works currently: If we have a predicate, the direction is enforced, but if there is no predicate it is not.  This is pretty much what we want, with two modifications:

1. There are cases when we want an undirected edge, even when the predicate is known (things like associated_with). @patrickkwang will make a separate issue about this.

2. @sudeepmandal (I think) will remove the arrowheads from edges without predicates in the UI. 

These don't really block COP testing, so moved the card to done.

**Comment by maximusunc** [comment]
Resolved in pull request #317
