### ISSUE TITLE
Edge clicks do not always work

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop#19]
Edge clicks do not always work, in terms of finding the mappings from entity to entity and revealing potential publications to support those edges (ie, evidence on right side of answers). Issue seems to be restricted to the first primary edge and can be overcome by clicking directly on the arrowhead, but this is difficult to achieve when exploring long paths. - KF

**Comment by patrickkwang** [comment]
This may be related to an issue Miles noted in the old repo:
"tooltip drop shadow intercepts edge clicks"

**Comment by karafecho** [comment]
Yes, that sounds correct.

**Comment by patrickkwang** [comment]
As of now, tooltips are gone, so I'll mark this closed unless someone has more issues.
