### ISSUE TITLE
CTD v3?

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#200]
CTD API has been updated with Jim's stuff.  I think that  there are still rows and patterns that need to be deconstructed before CTD is complete though.  e.g.

Metformin results in increased expression of and results in increased secretion of INS protein

I would expect that to generate a metformin increases_secretion_of INS, but that doesn't seem to be in the ctd api.

**Comment by balhoff** [comment]
I will look at that—I expected to get that one, so probably need to revise something.

**Comment by cbizon** [comment]
Maybe I just missed it- we should double check. But even if that one is correct, I think you mentioned that there are others that we didn't yet really know how to handle?

**Comment by balhoff** [comment]
I've figured out what's going wrong—I have a problem with the multi-interaction annotations. There is no wrong output, but some things are missing. Working on a fix.

**Comment by balhoff** [comment]
Done!
