### ISSUE TITLE
Answers >1000

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop#21]
I assume there's a plan to score and rank answers >1000?

**Comment by patrickkwang** [comment]
It's just a matter of changing a parameter, but these have to be handled by the browser on the client side, and it bogs down. It may be possible to load these on the fly by calling Python as the user scrolls. That will be a new technical challenge.

**Comment by kennethmorton** [comment]
This pushes us against a wall with file sizes. Some Answer Sets with 250 answers start to push 100mb in the standard JSON format. We have a proposal to change the standard format. Perhaps that is the best path forward.

**Comment by patrickkwang** [comment]
This is now configurable at the ranker API, with a default of 250. #81
