### ISSUE TITLE
Fix quick default api docs

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#223]
If you try to run the quick service using the default api docs args, it fails b/c those args have not been kept up to date:
1. identifiers are integers there, but should be e.g. "n0"
2. edges need id's but dont' have them there.

Kenny will fix in new version.

**Comment by cbizon** [comment]
I think this is done?

**Comment by kennethmorton** [comment]
Yeah the default input works just fine. There is certainly some general cleanup of the API docs that could be done. Particularly for some of the newer endpoints and the builder and ranker APIs. I will close this for now and possibly start another ticket specifically for that.
