### ISSUE TITLE
Hackathon: Property Queries

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#229]
Properties can be assigned to a node in the question spec, but right now those don't get passed along into the cypher query.  Hook this up so that we can add properties to queries for filtering.

**Comment by patrickkwang** [comment]
NCATS-Gamma/robokop-rank@4ed21fa3cfff5c80770a0016f93becd4206cb490
provides this capability from the ranker API.
* Only nodes that specify the filtering property and whose value is identical to the prescribed one are retained.
* Only string and boolean properties are supported, currently.

**Comment by kennethmorton** [comment]
For strings and booleans we can do equals straight forwardly. To allow for queries with numeric values we need some sort of language to specify operations (less-than, greater-than). Any ideas?

In either case I think we can allow or operations within a single property by specifying entries as a list.
