### ISSUE TITLE
Blackboard build failure

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop#23]
During yesterday's demo with NCATS, we initiated a new blackboard named "test", which ran from "particulate matter" (substance) to gene to "asthma" (disease), but it never appeared in the list of available blackboards. Not sure why. -KF

**Comment by patrickkwang** [comment]
It failed for me, too. Early in the build. @cbizon: Any ideas?

**Comment by cbizon** [comment]
Yeah, glad this got posted. I had forgotten already.  I'll try to build it and watch what happens.

**Comment by cbizon** [comment]
Though what I thought failed was just "particulate matter" to gene. (not to asthma). But @patrickkwang it sounds like you got a failure with asthma included as well.  Anyway, I'll try all of these queries and see what's going on...

**Comment by karafecho** [comment]
Actually, we may have tried this one: ozone -> gene -> asthma (from the ppt). I can't exactly remember. But yes, might be good to try all permutations.

**Comment by cbizon** [comment]
Will verify the following: 

1) "ozone/PM" -> Gene
2) "Ozone/PM" -> Gene -> Asthma
3) "ozone/PM" -> Gene -> PW
4) "Ozone/PM" -> Gene -> PW -> Gene
5) "Ozone/PM" -> Gene -> PW -> Gene -> Asthma

**Comment by cbizon** [comment]
Wellll, Ozone->Gene works fine in the backend, and I can see a graph written to neo4j.  

But running it in robokop.ncats.io, I got a "completed" green box, but the blackboard didn't show up in the list? @patrickkwang can you help?

**Comment by cbizon** [comment]
Ozone->Gene->Asthma works fine in both front and backend.

**Comment by patrickkwang** [comment]
Ozone/PM->Gene is fixed by f592cc87b369731272060f83cd81c1fc329f1c17.
I doubt this solves the original issue.

**Comment by patrickkwang** [comment]
PM->gene->asthma does appear to work now, though I'm still not sure what the original problem was or what solved it.
