### ISSUE TITLE
Refactor neo4j startup out of robokop-interfaces

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#232]
When the robokop-interfaces container starts, it rebuilds the type graph and index on neo4j.  But when there is more than one robokop-interfaces for different prod/dev/test builds all pointing at the same neo4j, that doesn't make much sense.

Instead, that stuff should come out of robokop-interfaces, and go somewhere else.  Maybe into the neo4j container itself?

**Comment by kennethmorton** [comment]
Within robokop-interfaces there is a script ./initialize_type_graph. This was being called by the container startup script. We removed this call from startup. We are now dependent on this initialization being made at some point. These instructions should go in the forth coming decimation on loading data into neo4j. I will close this issue and make a note on the currently open documentation issue
