### ISSUE TITLE
Update robokop/readme

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#236]
I don't think that the current readme.md file accurately represents getting a robokop up and running.

**Comment by cbizon** [comment]
As part of this, we should include information about building omnicorp, redis, and neo4j.   We should probably think about hosting somewhere versions of these databases for download, rather than making everybody crawl them.  Will be good/necessary for publication as well.

**Comment by kennethmorton** [comment]
I updated the readme to be up to date with respect to containers and environmental variables. This does not include anything on loading in DBs.

**Comment by kennethmorton** [comment]
Within robokop-interfaces there is a script ./initialize_type_graph. This was previously being called by the container startup script. We removed this call from startup. We are now dependent on this initialization being made at some point. These instructions should go in the forth coming decimation on loading data into neo4j.
