### ISSUE TITLE
Question layout hides edge

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#238]
If I have n0->n1, n1->n2, n0->n2, I get an image where n1 obscures the n0/n2 edge
![image](https://user-images.githubusercontent.com/10744350/53569780-f23d0680-3b32-11e9-8635-efdd80fab843.png)

Instead of 
![image](https://user-images.githubusercontent.com/10744350/53569809-0123b900-3b33-11e9-9a13-fc1ed5000fbc.png)

**Comment by kennethmorton** [comment]
Fixed in 7d4375346a25ce6d5f739723b821f02ebd6c33ce

<img width="404" alt="image" src="https://user-images.githubusercontent.com/1233522/53574672-076b6280-3b3e-11e9-84d8-36323276bd25.png">
