### ISSUE TITLE
Reorder results in name lookup

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#239]
If I look up Xeroderma Pigmentosum, the actual XP is at the bottom of the list, and all the subtypes are at the top.  Could we use the ontology to put higher nodes in mondo (or chebi etc) higher in the list?  Or use some kinds of heuristics like name length with shorter things higher?

**Comment by cbizon** [comment]
It would also be nice to order these by preferred prefix.  So for chemicals, I'd rather see chebis then chembls then pubchem (the same order in which we apply prefixes in synonymization).  Though I guess it gets tricky if there's a perfect match in one scheme and a poorer match in a better scheme...

**Comment by cbizon** [comment]
We should also merge concepts that are synonymous to us.   We could consider removing anything that isn't in the graph (gene searches are bad for this, because it returns a bunch of orthologs that we don't have and don't have the capacity to get).

**Comment by cbizon** [comment]
My complaint above is basically #98

**Comment by patrickkwang** [comment]
Name lookups now query our Neo4j KG. The resulting nodes are sorted by their search [score](https://lucene.apache.org/core/3_5_0/scoring.html) and labeled with their degree in the KG.

<img width="1022" alt="Screen Shot 2019-09-04 at 10 50 32 AM" src="https://user-images.githubusercontent.com/1263870/64266115-0e669980-cf02-11e9-9743-30dcab5acf3f.png">
