### ISSUE TITLE
Simpler Way to Specify a question

### ISSUE THREAD

**Issue by kennethmorton** [NCATS-Gamma/robokop#275]
A simplified cypher syntax would be pretty good for defining linear graphs. We could offer a little interpreter in the UI to make question generation quicker.

(gene id:HGNC)-(biological_process_or_activity)

This would then prepopulate the question editor.

Maybe this is a way to make question asking quicker. Or possibly this is a distraction and we should work to make questions more specific.

I think it would help in most cases.

**Comment by patrickkwang** [comment]
An English-based DSL that looks like NLP would serve the same purpose and be easier for nontechnical users.
