### ISSUE TITLE
Question Generalization: max_connectivity

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#277]
We have added the ability to limit maximum connectivity of a node in an answer.   It's ok but it's kind of harsh - if you lower it too much, you might not find any paths, and you don't really know how you should set it, so you end up starting small and dialing up until you find things, but you have to do that all yourself.

Somehow robokop should help coordinate this effort

**Comment by patrickkwang** [comment]
For ranking purposes, the informativeness weight should help. If computational expense is the issue, though, we'll need something else.

**Comment by patrickkwang** [comment]
Messenger supports specificity weighting now.
