### ISSUE TITLE
Add call information to edges

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#28]
With the changes to synonymization, there will now be multiple (potential) calls from a node to a service.  For instance, let's say that we have a disease node.  Maybe its identifier is MONDO:1234. But it has synonyms of DOID:456 and DOID:567.    When we call e.g. pharos, we have to decide which of the doids to send.  Probably we'll send both.  But there is a potential difference between them, and we need to track which of them was actually the input to the function for a given result.

**Comment by kennethmorton** [comment]
I imagine this is done/OBE. Re-open if I am wrong.
