### ISSUE TITLE
Publish robokop-kgb

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#280]
We want to submit a bioinformatics application note about robokop-kg and kgb

**Comment by cbizon** [comment]
GigaScience?  (7.267)
Nature Scientific Data? (5.305)
PLOS Compuational Biology (3.95)
Genomics, Proteomics, and Bioinformatics (6.6)

**Comment by karafecho** [comment]
[npj Digital Medicine](https://www.nature.com/npjdigitalmed/) is another option, although this is a new journal.

**Comment by karafecho** [comment]
In addition, we might consider the [AMIA 2020 Informatics Summit](https://www.amia.org/summit2020/call-for-participation).

**Comment by cbizon** [comment]
> In addition, we might consider the [AMIA 2020 Informatics Summit](https://www.amia.org/summit2020/call-for-participation).

Deadline for submission is August 15.

For most of these, we should be able to expand the text somewhat to make it more digestible.
