### ISSUE TITLE
Straighten out robokop/robokop-interfaces dependencies

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#283]
RIght now, you cannot just run robokop interfaces. But since we're going to publish it independently, it makes sense to make it so that it can run independently.  I think (but am not certain) that this only involved moving the redis and neo4j containers from one repo to another and whatever associated scripts need to change.

**Comment by patrickkwang** [comment]
Done. https://github.com/NCATS-Gamma/robokop-interfaces/pull/10
