### ISSUE TITLE
display node properties

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#289]
Can we display node properties in the UI?

**Comment by maximusunc** [comment]
@cbizon is this a different feature from issue #302 ?

**Comment by cbizon** [comment]
Yes, this one is when looking at an answer.   The nodes that come back in an answer have a lot of properties (especially the chemicals, but also the genes, diseases, etc). It might be stuff like the chemical structure or the gene position etc.  It's nice to be able to look at that stuff.  So for instance, in the neo4j browser, you can click on a node and see the properties at the bottom of the window.

![image](https://user-images.githubusercontent.com/10744350/58259658-f730e100-7d42-11e9-8838-05fe786b9625.png)

**Comment by kennethmorton** [comment]
I believe we can accomplish this with more liberal use of graph display node hover. I think we can also add an edge hover.

**Comment by kennethmorton** [comment]
We should also put this in the edge explorer modal.

**Comment by maximusunc** [comment]
A lot of extra properties have been added to the node hovers as well as the edge explorer modal. PR #367
