### ISSUE TITLE
Save function

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop#297]
In the question builder, it's not intuitive that users need to save each step of the build. Is it possible for users to build the full question before saving? In other words, one save, instead of multiple saves.

**Comment by cbizon** [comment]
Agreed, for the old interface.  On the new interface, I think it's less of a problem?   You just use that button to close the dialog.  Would some different text on the button be better?

**Comment by karafecho** [comment]
I think the new UI has clarified this issue, but it might be good to change the text to "save query" or something like that.
