### ISSUE TITLE
Help users with lookup

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#306]
Right now, we lookup names, and show the users a list of possibilities, and the user has to choose.  It's not optimal and we can maybe help.  We do show links out to name resolvers, which is helpful, but: most of the time we have this problem it is for chemicals and the name resolvers don't handle pubmed.

So there some simple things - #239 is related and suggests reordering which mostly helps with diseases.  I also think we could bring in the ontologies to show which names are more general/specific.  

We might also want to allow the option to "select all" and have it fire off multiple queries (or an or) for that node.

But the single most important thing we could show is whether that node is connected to anything in our data, and how much and what kinds of things.   Because that is what is going to decide whether the query is worth doing most of the time....

**Comment by patrickkwang** [comment]
https://github.com/NCATS-Gamma/robokop-rank/commit/69916f228c54cc54614379cb6fa9ebc4dd95e1ae should help.

**Comment by patrickkwang** [comment]
https://github.com/NCATS-Gamma/robokop/issues/239#issuecomment-527937407
