### ISSUE TITLE
Adding constraints slows down results?

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#308]
I have a query (there's an example now called multi-cleaner) That is basically
(named chemical 1)-(unspecified gene 1)-(colitis)
(named chemical 2)-(unspecified gene 2)-(colitis)
(named chemical 3)-(unspecified gene 3)-(colitis)

It runs pretty quickly.

Then I tried "multi-cleaner with process" which adds a single biological_process_or_activity node connected to all 3 genes.

This query takes a long time.  I havent' tested enough to determine whether this is just bad luck in terms of other things running etc, or something reproducable.  But it seems to me that this additional node should speed up rather than slow down the query...

**Comment by patrickkwang** [comment]
I'm not terribly surprised that it takes longer. Here's one possible execution plan: start at colitis, get connected genes, get connected chemicals, filter by chemical curie, get connected processes, filter by process curie. I can look at the actual execution plan if you can provide specific examples of the named nodes (curies).

**Comment by cbizon** [comment]
machine question attached

[robokopMachineQuestion.json.txt](https://github.com/NCATS-Gamma/robokop/files/3141643/robokopMachineQuestion.json.txt)

**Comment by patrickkwang** [comment]
https://github.com/NCATS-Gamma/robokop-rank/commit/7334c36926ebe73f8e5ffdc9320f5f23c98f0982
Note: this is no guarantee that adding extra edges will not slow down the query; that may be unavoidable. But it should help.
