### ISSUE TITLE
Add id property to edges?

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Gamma/robokop#309]
When we bind question elements to KG elements, we reference KG edges by their Neo4j internal id. When we download the question-specific KG, we plug these ids into the local KG as a property. The problem is that it's not invertible: we can't create Neo4j edges with specified ids, which is a must when querying against a user-specified KG. We could query different ways in different cases, or just generate ids for all of our Neo4j edges, and eliminate the dependence on Neo4j internal ids.

**Comment by cbizon** [comment]
If we stop using neo4j ids, could we make the id some kind of hash of the edge, so that we could guarantee that the same edge would get the same id in different versions of the database?   As it is, we don't really want to blow away the entire db and start again, even when it's the most straightforward way to fix some things...

**Comment by patrickkwang** [comment]
Yes. All we need to translate between different representations of the graph is settable unique ids, but if they can encode some semantic information, that would be great, too. There should be no need to wipe out the database in order to add a property to each edge. I think one Cypher command should do it; APOC has some hashing utilities. I'll work out what that should be and others can review before we do anything to the deployed KG.

**Comment by patrickkwang** [comment]
While we're messing around with the Neo4j, maybe we should take a minute to complete #70, too.

**Comment by cbizon** [comment]
Agreed on #70

**Comment by patrickkwang** [comment]
This should do it: `MATCH ()-[e]-() SET e.id=apoc.util.md5([startNode(e).id, endNode(e).id, type(e)])`

I think perhaps I was confused before about which "database" @cbizon was referring to. If we change how we query the Neo4j for edges, we will also have to modify saved answers in the Postgres database. Options:
1. write a script to modify the saved edge ids in the Postgres DB
2. wipe out the Postgres DB
3. postpone resolution of this issue

**Comment by patrickkwang** [comment]
https://github.com/NCATS-Gamma/robokop-rank/commit/e9a471cdc8773ed6ce71a085977e51f9346e9a5c
https://github.com/NCATS-Gamma/robokop-interfaces/commit/1dc3de55dce92e2745912a6d6b1e8bc70bb8a323
