### ISSUE TITLE
Expose parameters in simple interfaces

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#310]
The "simple" tool pages are great, but they don't expose the parameters for the functions.  That makes them a bit tough to use: you really need the cutoffs for the similarity and enrich, and the directionality stuff for expand.

**Comment by maximusunc** [comment]
similarity and enriched parameters have been added in pull request #315

**Comment by maximusunc** [comment]
The rest are being added in pull request #317

**Comment by cbizon** [comment]
This looks done?  Can it be closed?

**Comment by maximusunc** [comment]
Yeah, closing this issue.
