### ISSUE TITLE
Re-integrate crawlers

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#319]
There are a couple of new data sources that are only going into obesity hub, but we should bring them back to regular robokop (gwas catalog, gtex, etc).  This does not apply to the GWAS data...

But the process of loading this stuff should be re-integrated to the regular crawler and pushed to the various robokop dbs.

**Comment by EvanDietzMorris** [comment]
This is mostly done but we still need to address accessing the GTEX data from the container in a more elegant way, which is related to issue #382
