### ISSUE TITLE
query builder freaks out on certain types

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#349]
In the query builder, if you use the 'main' types, then everything is fine, but if you try to use certain types, the ui sort of unhelpfully doesn't really let you, but it's not obvious why or what is happening.  For instance, if you try to use 'drug' or 'disease or phenotypic feature', you will see the behavior.

Maybe we should populate based on  labels that exist in the neo4j?

**Comment by maximusunc** [comment]
Fixed in merge #357 .
