### ISSUE TITLE
populate node types from biolink model

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#35]
Currently, we keep a list of hand-crafted node types in robokop-interfaces and use them to tag nodes in neo4j and in the queries and so on.  But we want to populate that (or a similar thing) directly from the biolink model, (possibly with local additions).

**Comment by cbizon** [comment]
This works well.   My main problem is that we're modifying biolink-model , which is going to be changing outside as well, so keeping stuff aligned will be bad.  We probably want to have an additional model that imports biolink-model, but contains our additions.

Similarly, I think that the concept/id type should perhaps live somewhere besides this model?

**Comment by stevencox** [comment]
I think this is describing an overlay - a parallel model with identical conceptual structure that overrides whatever's in the original. Is that right?

By concept/id type living somewhere else - do you mean moving id_prefix to the overlay or something more involved?

**Comment by cbizon** [comment]
I think that an overlay is one way to look at this.  Another is more that we might want additional types, but without overriding.  My impression is that this sort of thing is done frequently in the semantic world, where maybe an ontology is good, but you want some additional terms, so you just make those terms, and refer to the original set of terms as ancestors of yours.  If we say that we're never going to override, then I think thinks get simpler.

For concept/id type, I think that this mapping should probably live somewhere else, though maybe not anywhere more involved.  It's basically just a many-to-many relationship that we want to track.  It's not independent of the model itself, but if e.g. biolink is not tracking the prefixes in its yaml then I think we should not either...

**Comment by stevencox** [comment]
Ok but I think they are tracking id_prefixes in [biolink-model](https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml), right?

**Comment by cbizon** [comment]
Hmm - there are some in there, but my impression is that it is far from complete.   You added quite a few, as well, right?  Not too sure how to handle this one.

**Comment by stevencox** [comment]
I added ones we used that I couldn't find represented. So I added instances of id prefixes but the idea of associating prefixes and concepts was already part of biolink-model.

**Comment by cbizon** [comment]
OK, so sounds like for prefixes/concepts we rely on the model to tell us, and we try to get what we need incorporated into the model, so that we don't have a biolink-model-local modifying biolink-model entries?

**Comment by cbizon** [comment]
+1

**Comment by stevencox** [comment]
This [file](https://github.com/NCATS-Gamma/robokop-interfaces/blob/master/greent/conf/biolink-model_overlay.yaml) (is just test data and otherwise total rubbish) that should be read by the [loader](https://github.com/NCATS-Gamma/robokop-interfaces/blob/master/greent/concept.py#L76) and applied as an overlay to the official biolink-model. 

I figure we can put Gamma specific stuff there. So that's the second list item from the comment above.

And the main [biolink-model](https://github.com/NCATS-Gamma/robokop-interfaces/blob/master/greent/conf/biolink-model.yaml) file gets synced with the biolink-model repo fork periodically. 

And that's the first list item from the comment above.

**Comment by cbizon** [comment]
That sounds good.  We should be able to go ahead and implement some gamma-specific stuff like genetic_condition and drug.

**Comment by stevencox** [comment]
Cool. Speaking of biolink model, is someone already adding predicates to the knowledge map and graph? Seems like we should have those, eh?

**Comment by stevencox** [comment]
Predicate lists:
* [Minimal](https://docs.google.com/spreadsheets/d/1zXitcR1QjHyh6WocukgshSR7IoAVg7MJQG-HNh96Jec/edit#gid=3366698)
* [Maximal](https://docs.google.com/spreadsheets/d/1zXitcR1QjHyh6WocukgshSR7IoAVg7MJQG-HNh96Jec/edit#gid=421374962)

The KG Standardization team selected the minimal list.

Cogitate on how and if that constrains us. Do we represent internally as maximal but export to minimal?

**Comment by cbizon** [comment]
On predicates - It seems to be that the KG standard is to use a minimal predicate as the neo4j edge type.  I'd suggest that we add one or more maximal predicates to a 'predicates' property on the edge.

On biolink - just a note that we still need to extricate our changes from the original model into the overlay file. 

Also a question about the overlay: How overlay-ish is it?  Does it overwrite the biolink model at the concept level?  So if I want to add identifiers, do I need to copy the entire concept into the overlay and add the identifiers, or can I add a more minimal version of the concept to the overlay?

**Comment by stevencox** [comment]
Predicates: So I think you're saying manage a KG-standards compliant minimal predicate on each edge. And manage a more granular predicate from the maximal list on each edge also. And export the minimal edge for KG-standards purposes. Is that right?

Right, I'll look at teasing apart our biolink-model changes next.

I have to think about this some more but I believe the overlay is a stomp, not a surgery. So one would have to replicate the entire sub-hierarchy beneath a changed node.

**Comment by kennethmorton** [comment]
I believe this is mostly done, or at least OBE, any remaining problems may be more directly discussed in additional issues. Re-open if I am wrong.
