### ISSUE TITLE
Can't add an edge between 2 "Named Thing" nodes

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#354]
In the query builder, I want to build a path of 'named things' but the edge dialog won't accept an edge between two named things.  I have not checked to see if this is true to any types (like two chemicals or two genes) or whether it's specific to named things.

**Comment by maximusunc** [comment]
Patched in merge #357 . It won't error when adding an edge to a "named thing" node. When creating the node, you also can't specify it with a curie. And when making an edge, you won't be able to specify any predicates. I'm happy to reopen this issue if this isn't wanted behavior or there are other improvements to be made.
