### ISSUE TITLE
Answerset loading slow

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#355]
For example: 
https://robokop.renci.org/a/bc0fd028-2646-4a4a-a444-cbddb702636f_085e6000-6522-4311-8cb0-5c10197c4c0e/
Only has 11 answers, and each answer is only 4 nodes & 3 edges, but it takes about 24 seconds to load the answer set.

**Comment by patrickkwang** [comment]
I was wondering when someone would notice this. It's a known issue caused by the internal id -> 'id' property switch. Basically, Neo4j optimizes looking up edges by their internal ids, but we have to be smarter about looking things up by the 'id' property. A couple of solutions are being tested.

**Comment by patrickkwang** [comment]
https://github.com/NCATS-Gamma/robokop-rank/commit/1762eb34c2ea9d4f947511cf9445fa4d7b11e2b2
Now uses a fulltext index to expedite edge lookups by the 'id' property. The index was generated manually, and must be updated if any edges with new predicates (Neo4j types) are added. Here is the command used to do it the first time:
`CALL db.index.fulltext.createRelationshipIndex('edge_id_index', ['decreases_uptake_of', 'occurs_in', 'metabolite_to_disease', 'has_output', 'increases_expression_of', 'exposures', 'increases_transport_of', 'affects_response_to', 'decreases_activity_of', 'sequence_variant_to_gene', 'directly_interacts_with', 'decreases_mutation_rate_of', 'metabolite_to_metabolite', 'affects_uptake_of', 'decreases_localization_of', 'decreases_expression_of', 'gene_to_gene_family', 'increases_localization_of', 'regulates', 'metabolite_to_gene', 'increases_secretion_of', 'affects_expression_of', 'interacts_with', 'disease_has_basis_in', 'results_in_motion_of', 'pathway_to_gene', 'affects_molecular_modification_of', 'gene_get_drug', 'affects_localization_of', 'capable_of', 'posetively_regulates', 'cell_type_to_anatomy', 'anatomy_to_cell_type', 'increases_uptake_of', 'decreases_metabolic_processing_of', 'affects_splicing_of', 'positively_regulates__entity_to_entity', 'affects_metabolic_processing_of', 'increases_splicing_of', 'gene_to_drug', 'disease_to_gene', 'has_input', 'disease_to_chemical', 'phenotype_to_biological_process_or_activity', 'contributes_to', 'gene_to_sequence_variant', 'affects_mutation_rate_of', 'affects_stability_of', 'adverse_events', 'actively_involved_in', 'biomarker_for', 'participates_in', 'disease_to_metabolite', 'disease_to_gene_association', 'increases_response_to', 'affects_secretion_of', 'increases_synthesis_of', 'bio_process_chemical_substance', 'contraindicated_for', 'pathway_to_metabolite', 'increases_stability_of', 'bio_process_cell_type', 'affects_transport_of', 'derives_into', 'treats', 'anatomy_to_gene', 'results_in_developmental_progression_of', 'gene_to_anatomy', 'increases_activity_of', 'biological_process_or_activity', 'negatively_regulates__entity_to_entity', 'anatomy_to_phenotype', 'increases_molecular_modification_of', 'affects_synthesis_of', 'increases_metabolic_processing_of', 'sequence_variant_to_disease_or_phenotypic_feature', 'has_phenotype', 'negatively_regulates', 'related_to', 'gene_to_pathway', 'increases_mutation_rate_of', 'enzyme_to_metabolite', 'gene_associated_with_condition', 'affects', 'causes', 'decreases_transport_of', 'has_completed', 'gene_get_phenotype', 'phenotype_to_anatomy', 'has_participant', 'drug_to_gene', 'disease_to_biological_process_or_activity', 'part_of', 'decreases_response_to', 'has_not_completed', 'gene_to_disease', 'decreases_degradation_of', 'bio_process_gene', 'drugcentral', 'metabolite_to_pathway', 'decreases_synthesis_of', 'located_in', 'affects_abundance_of', 'disease_to_phenotype', 'increases_degradation_of', 'phenotype_to_disease', 'chemical_targets_gene', 'affects_degradation_of', 'chemical_to_gene', 'decreases_molecular_modification_of', 'disrupts', 'decreases_stability_of', 'affects_activity_of', 'disease_or_phenotypic_feature_to_sequence_variant', 'causes_adverse_event', 'decreases_secretion_of', 'prevents', 'disease_to_anatomical_entity'], ['id'], {analyzer: 'keyword'})`
