### ISSUE TITLE
gray screen in question builder

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#369]
From Mark via slack:
Hey, odd problem I've hit a few times with Robokop.  When using the web interface and trying to edit a question graph, sometimes the screen will gray after clicking a node or edge to edit it, but the window to actually edit it never comes up.  Haven't really figured out a way to get around it consistently.  It seems that once it has happened once, it will continue to happen and starting over in a new tab is the only way forward (the new tab continues to do this sometimes too)
Any idea what might be causing that or how to work around it?  I'm on Chrome for Mac and have tried disabling my adblocker.  Anything else I can try on my end?

This is (I think) always been on trying to "Ask a New Question" to edit an old one
1:57 PM
So, maybe it's a thing with the older questions not being cached
1:57 PM
It's relatively new; last week or so

bizon 1:58 PM
OK, thanks for the report.   If you go back to the original question and try to edit it again, does the behavior always happen?
￼
markw 1:59 PM
Seems like it does, but I haven't tested rigorously
1:59 PM
After the KGS call, I can try to reproduce the error more deliberately and see if it always occurs with some graphs or not

**Comment by cbizon** [comment]
Followup:
Ah, I think I've found the (or at least _a_) common denominator for questions that this issue occurs for

So far, I'm 2 for 2 on this occurring when I try to edit a `named_thing` node
I've closed out the tabs, and come back in to try again and it still occurs
It did not happen for a different question I tried to edit which contained no `named_thing` nodes

**Comment by maximusunc** [comment]
We just deployed, and it seems to have fixed the issue. I'm going to close this issue, but if Mark experiences it again, just reopen and we'll look back into it.
