### ISSUE TITLE
Implement HttpCache

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#37]
We are going to move from a single blackboard per question to a large local knowledge graph that is maintained and updated over time.    When a new query is run, we want to run the build process, but we want to speed up the process by making use of previously cached results.

Rather than the build process having to either be told about what has previously been done or query the neo4j knowledge graph to find out, we want to implement an http cache, so that we will just return cached results.  The effectiveness of this strategy will be dependent on moving non-http (sparql) endpoints to http endpoints.

**Comment by stevencox** [comment]
Docs are in the [readme](https://github.com/NCATS-Gamma/robokop-interfaces).

**Comment by stevencox** [comment]
There's always more one can do with and to a cache.

But we cache web service calls during query execution, we cache synonyms, and we've added a cached service base class.
