### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop#372]
IMPORTANT Comment from reviewer of _Bioinformatics_ App Note:

* Accessing http://robokop.renci.org/apidocs leads to internal server error ("The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.")

**Comment by kennethmorton** [comment]
Without a trailing slash (as we included in the paper) doesn't work. 
https://robokop.renci.org/apidocs/
Works just fine. I know we had problems with this within the flask, flasker issues, I wonder if we can just reroute at the nginx level.
