### ISSUE TITLE
Review Evan’s updates to the loading strategy document.

### ISSUE THREAD

**Issue by bryttanytodd** [NCATS-Gamma/robokop#377]
the said file can be located at: https://docs.google.com/document/d/1-G-9uvsZDDBhYCsjbtd9tQKj1IIO4hVK-pPsy_7AQC0/edit

**Comment by PhillipsOwen** [comment]
Document reviewed. Additions made to explicitly declare the entry points for loading GTEx data (2.a.) and MyVariant/Ensembl data caching (4. b-e).
