### ISSUE TITLE
Look into Synonymization errors

### ISSUE THREAD

**Issue by YaphetKG** [NCATS-Gamma/robokop#385]
There seems to be cases where nodes that are quite different end up being synonyms (i.e have each other ids in list of equivalent ids).  Example case was 'Zinc Sulfate' vs 'Almunium tri chloride'.
``MATCH (c:chemical_substance) where any (x in c.equivalent_identifiers where x = 'CHEBI:35176' ) return c.name``

**Comment by cbizon** [comment]
In the process of adding a new chemical prefix (for guide to pharmacology), I've rerun the chemical synonymizer.  The concord file that gets produced seems more correct.  I think we might need a completely fresh rebuild.

**Comment by cbizon** [comment]
It's still processing, but  in the current built, this query only returns 'Zinc Sulfate' which is the correct response.
