### ISSUE TITLE
Supervisors all try to auto-restart

### ISSUE THREAD

**Issue by maximusunc** [NCATS-Gamma/robokop#389]
They probably don't need to auto-restart, because if a server is down then users "might" start to get thousands of emails of a failed connection.

**Comment by maximusunc** [comment]
In the supervisord.conf files under each [program:xxx], we can just place `autorestart=false`.

**Comment by patrickkwang** [comment]
Done for manager.

**Comment by patrickkwang** [comment]
02a04336cddd554ab6026c7f17b16340020f31dd
https://github.com/NCATS-Gamma/robokop-rank/commit/47b67bf390f4d8aec69cf2516801f69b56f05f19
https://github.com/NCATS-Gamma/robokop-interfaces/commit/a26562f897995890d457181ae457fff0a52418a8
