### ISSUE TITLE
smartapi for uberongraph

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#39]
Right now, we call uberongraph as a sparql endpoint. The main problem there is that it evades any http caching. So we'd like to wrap this in a smart api, which will also allow us to expose it in the translator registry, etc.

**Comment by cbizon** [comment]
If we had this, would our anatomy results be annotated with "anatomical entity" or "gross anatomical feature?"

**Comment by balhoff** [comment]
I guess "anatomical entity". But don't you also use this to query phenotypes?

**Comment by kennethmorton** [comment]
Status check? This may be OBE or finished.

**Comment by cbizon** [comment]
I think that we've decide that sparql is a valid endpoint and we're going to go with it for the time being.
