### ISSUE TITLE
What is the estrogen receptor (ranking problem)

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#396]
Though people often refer to 'estrogen', that is not a particular chemical, but a family of chemicals.   There are a few naturally occurring (endogenous) versions in humans, and a bunch of other chemicals that get lumped in there, either because they come from other organisms or they have the same biological activity.

In CHEBI, estrogen is a role, meaning that in robokopdb, we have an "estrogen" property.  There are about 70 compounds with that property...

Estrogens interact with a bunch of things, but there is one main receptor for them.  It's ESR1 (Estrogen Receptor 1) .  

The question is - can you tell what is the natural receptor of estrogens?  Can you find ESR1 from among all the other genes that all the estrogens interact with.

https://robokop.renci.org/a/8571896c-fbb8-4216-b230-498505c18843_2a55b040-a76b-487e-8b2c-f639ce335c99/ is an attempt.   It's (set of chemicals with estrogen property)-[increases activity of]-(gene).  I also tried [directly interacts with] to similar results.   Even though there are many chemicals interacting with ESR1, and some of them very strongly, ESR1 is way way down in the list.

**Comment by patrickkwang** [comment]
https://robokop.renci.org/a/6eb1bae2-9549-4217-9e87-e9b46e30a1b2_48b0a07c-37ad-4b81-9d96-2f143fdad8b2/
