### ISSUE TITLE
name lookup doesn't substring search?

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#398]
Add a node, select "chemical substance" and make it specific.

In the lookup, type "vasopressi".  Nothing is found.  Add an "n".  Now vasopressin is found.  So apparently this is only matching on complete names?

**Comment by kennethmorton** [comment]
Search/lookup is really starting to be a high friction point for users. We need to tie it to the knowledge graph contents. @patrickkwang you are the most knowledgeable on Neo4j indexing. How can we do this speedy?

**Comment by patrickkwang** [comment]
We could do a full text search over the node `name`s and return the associated `id`s.

**Comment by cbizon** [comment]
The current search isn't looking into the neo4j, which has its downsides, but it also has the upside that it can find (text) synonyms that we aren't including in neo4j.
