### ISSUE TITLE
Missing cellular components

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#399]
According to quickgo, there should be a part-of relationship between AVPR2 and various membrane-related cellular component terms.  But we don't have those.

**Comment by cbizon** [comment]
I don't see a gene-cellularcomponent link in rosetta.yaml so I'm a little confused.

**Comment by cbizon** [comment]
Need to incorporate quickgo as service for gene->cc links

**Comment by YaphetKG** [comment]
New crawl has finished. Looks like quickgo is returning some cellular component nodes. 
![image](https://user-images.githubusercontent.com/45075777/61959675-e8a8b500-af91-11e9-90e1-dae566851c95.png)
