### ISSUE TITLE
NGINX Subservice APIDocs issues

### ISSUE THREAD

**Issue by kennethmorton** [NCATS-Gamma/robokop#402]
Using any of the UI on https://robokop.renci.org/ranker/apidocs/ does not correctly route the internal requests. For example the cypher answers service posts to

https://robokop.renci.org/api/cypher/answers/?max_connectivity=0

when really it should post to

https://robokop.renci.org/ranker/apidocs/cypher/answers/?max_connectivity=0

Is there a way to configure the individual swagger / flasgger things to do this correctly behind NGINX?

**Comment by kennethmorton** [comment]
The same is true for interfaces, I assume.

**Comment by patrickkwang** [comment]
Maybe this:
https://github.com/rochacbruno/flasgger#behind-a-reverse-proxy

**Comment by YaphetKG** [comment]
We have had a header coming from Nginx if you take a look at /robokop/deploy/proxy/configs/default.conf.template , the ranker and interfaces all have a header called 'X-Swagger-Prefix' set to '/ranker' and '/builder'

**Comment by YaphetKG** [comment]
I have the changes in place for ranker and builder to read the 'X-Swagger-Prefix' from the headers and apply it if present, @patrickkwang  Thanks for the pointer.
