### ISSUE TITLE
Models for nodes & edges

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#41]
We need to develop a common understanding of what nodes & edges look like in our knowledge graph, and then we need to implement that understanding.   I will take a first shot at defining the nodes, edges, and directional behavior here, and then invite others to comment.  Once we have things sorted out, we will move to implementation.

**Comment by cbizon** [comment]
A couple of preliminaries:  properties in neo4j can only be primitives (numeric, string, boolean) or lists of primitives.  No maps, and no nesting.  So, for instance, if you had json, you'd have to smush it into a string value, and lose the structure.  Also, there's no datetime type.  We either need a string format that we parse or an integer timestamp.

Also, the assumption here is that we don't want to use neo4j to handle the caching of results.   This plays a little bit into how we want to do datetime properties.  If the goal is to do queries where we need things like "give me edges older than X", then an int property is best.  But otherwise, using a string representation is better for readability.

Edge directionality:  Do we want edges to point from the input of a call to its output?  Or do we want it to point from the subject of a relationship to the object?  These will often be the same, but not always.  One possibility that we had discussed is the idea of materializing edges that point both directions with the inverse of the predicate. Also we have undirected relationships (co-occurence in papers), but neo4j does not allow for these.  

The guidance from neo4j seems to be that you should not materialize the inverse relationships and you should not make two edges to indicate undirected relationships, because it slows down traversals too much.  Instead, things should be handled in queries.

My inclination is that subject->object is the most natural way to do this.  If we think it useful, we can try to  invert edges where necessary so that subject->object also matches the call direction, but I think that we cannot do that in general, so it's probably not worth the trouble.

The question comes down to: what are the directions used for in querying, and the upshot, I think, is that we don't really care about direction when we go to the graph and construct our answer pathways.

**Comment by cbizon** [comment]
For node:
(label): node_type from biolink model
id: The main identifier for this entity, written as a curie (e.g. "HGNC:1234")
equivalent_identifiers: A list of other identifiers, as curies
name: String giving a display name for this entity.  It should usually be the rdf:label of the id.
synonym: A list of other string names for this entity
pmid_count: An integer counting the total number of times this entity appears in the literature.

Q1: If we are using label to handle node_type, how do we want to handle the type hierarchy? So if we make a node with label "genetic_condition", we might like to find that node when looking for a "disease". There are at least 3 approaches: 
A) Just have a single label: "genetic_condition" and incorporate the hierarchy on the query side only.
 B) Have a single label: genetic_condition, and later, if needed, add a different node with the same information, but a "disease" label.  
C) Add all superclass types as extra labels on the node.  So this node would have labels "genetic_condition" and "disease" (and any superclasses of disease etc).

Q2. Do we want to keep any information about queries that reference this node, either in the build or answer process?  I don't have a clear use case for this.

**Comment by cbizon** [comment]
Edge: 
 (label): "Translation"|"Support
 predicate: Identifier of the predicate (like RO:001325)
 predicate_label: string identifier of the predicate label: "inhibits"
 edge_source: representation of the call that produced the edge
 input: list of identifiers that was sent to edge source to produce the edge
 update_time: the most recent time that this edge has been updated
 references: list of pmid strings

Q: what is the level of specificity for the edge source?  Is this a URL? Or a python function? Or something else?

Q: Is there any reason to save the initial creation time of the edge?
 
Q: Is support/translation the correct thing to do with the label?  The idea is that this will be one of the most common filters for queries, so it makes sense to make the edge label.

**Comment by patrickkwang** [comment]
My expectation has been that we will some day use the predicates somehow, and when that day comes I think we'll want them to be the labels. We can add support edges with a predicate like "literature_association".

**Comment by cbizon** [comment]
Yeah, absolutely we will use the predicates, hopefully sooner rather than later!   I went back and forth on whether the predicate should be the label or not, and I'm still fine making it that.  

The main reason I thought of having the label be whether or not an edge was a support edge had to do with the main query that we're going to do, which is pulling answers out (?).      There are going to be a lot of support edges, and we want to be able to query only along non support edges.  But if they all have a bunch of different labels, then how do we do that?   Can you do ()-[r:NOT(literature_association)]-()?   Is this a concern or am I barking up the wrong tree?

Couple smaller points:

Should the label be the identifier for the predicate (like the URI from RO) or the label of the predicate (like "inhibits").   Identifier I think is better, but in cases where there is not a term in an ontology that we want to use, we'll end up minting our own, I guess.

The other thing is that predicates also have parent/child relations, so we get into the same questions as we do for nodes about how to implement that.  And for edges, you can only have one label, so the idea of tagging a single edge with every ancestor is not usable.   We could, I guess, have a property that's a list of ancestor predicates, whether predicate is the label or not...

**Comment by patrickkwang** [comment]
I'm expecting that pulling answers out will involve mostly specified predicates. In places where the predicates are not specified in the question, all we care about is that two things are ... associated somehow. In which case maybe including support edges (with reasonably high cooccurrence) is not a bad idea...

**Comment by cbizon** [comment]
Right, but we have said that the nodes will potentially be fully connected by support edges, which worries me for finding paths.  Feels like it will be incredibly slow to have to check property values to build the answer.  But my cypher intuition is pretty low.
