### ISSUE TITLE
mychem indications edge_source

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Gamma/robokop#413]
https://github.com/NCATS-Gamma/robokop-interfaces/blob/master/greent/services/mychem.py#L42
It looks like we assign drug indications the edge source `mychem.get_adverse_events`, which seems wrong.
Helpfully pointed out by @MarkDWilliams.

**Comment by cbizon** [comment]
Mychem get_adverse_events is getting adverse events data from aeolus.  The problem with adverse events data is that people sometimes report whatever the drug is meant to treat as an adverse event.  So if you have a pill for headaches, and you take the pill and get a headache anyway, you might report "headache" as an adverse event.  

To allow people to filter these out, get_adverse_events also includes a list of indications for the drugs.  So we go ahead and include those.   We are giving them 'treats' predicates, but the source of the info is the get_adverse_events call.  i.e. they are coming in as a side effect (no pun intended).  

So I think that this is ok, unless I am missing something.

**Comment by patrickkwang** [comment]
Okay. So `edge_source` is unique to a specific remote API call, and may not have a one-to-one correspondence with the predicate.
