### ISSUE TITLE
macOS group id issue

### ISSUE THREAD

**Issue by EvanDietzMorris** [NCATS-Gamma/robokop#415]
Users on macOS will often have the default group id / GID of 20 (staff). That ID conflicts with a default group inside the docker containers, leading to a build error with the recommended deployment steps. (RUN groupadd -g $GID murphy) causes (groupadd: GID '20' already exists). 

This is not very hard to avoid but should be at least be addressed in the documentation if nothing else. One option is to have users change their local primary group id to something > 500. Another is to allow non-unique group ids with (RUN groupadd -o -g $GID murphy) in the Dockerfile.

**Comment by patrickkwang** [comment]
`groupadd -o` sounds like a good solution. The murphy user could gain some extra permissions this way, a potential security vulnerability, but I think a relatively minor one.

@EvanDietzMorris, would you like to make a pull request?

**Comment by patrickkwang** [comment]
#422
