### ISSUE TITLE
Move to common knowledge graph

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#42]
Results are currently stored in the knowledge graph on a per-question basis.  We use a label to associate nodes with a particular result.  We want to remove those labels and merge results into the previously existing graph.

This will probably also require changes to the UI/reasoning side.

**Comment by cbizon** [comment]
This is now working, in that node labels now simply include the concept type, not a question identifier.  

Nodes are identified by their identifier property.   If new labels are needed, they are added, and if properties differ, then the node properties are overwritten.

Edges are identified by their end nodes and the source/function properties.  Rather than checking all the properties, if we find a matching node, we just delete the old one and replace it with the new one.

Leaving this open since there will be Reasoner/UI consequences to deal with.

**Comment by patrickkwang** [comment]
Reasoner/UI consequences have been dealt with.
