### ISSUE TITLE
Can't specify gene family in UI

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#424]
Trying to run a query for the AMIA paper.   We have a query that runs in quick (The one in this notebook: https://github.com/ncats/translator-workflows/blob/master/greengamma/workflow3/MCATS_Immune_Question1_MHC.ipynb )

The query starts with a gene family identified by its ID.  I can't make the ROBOKOP UI create such a node:

![image](https://user-images.githubusercontent.com/10744350/63093541-b1477b80-bf33-11e9-993f-97ab10588c1c.png)

Save is grayed out and when I mouse over it, I get a message about fixing invalid entries (doesnt' indicate what that is)

**Comment by maximusunc** [comment]
Bug fixed in commit https://github.com/NCATS-Gamma/robokop/commit/5666c9fec0dc4f274c3ee46202115d7331eb3e35. Regex wasn't accounting for periods in the curie.
