### ISSUE TITLE
Papers repeated in the UI

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#433]
See example image in #429

**Comment by cbizon** [comment]
That definitely looks weird.  That call should be hitting the redis cache, where things look fine:

['PMID:3602230', 'PMID:873718', 'PMID:11830756', 'PMID:26288288', 'PMID:4070644', 'PMID:6356192', 'PMID:8272443', 'PMID:8255983', 'PMID:2829786', 'PMID:2824589']

**Comment by cbizon** [comment]
Apparently the api doesn't hit the cache.  Looking in the cache for adding support edges all happens in the ranker.  I wonder if that should be moved into the omnicorp supporter instead so that any caller will get the caching automatically...

Anyway, either a problem with the postgres, or the postgres query

**Comment by cbizon** [comment]
There are dup rows in the omnicorp postgres table:

```
robokop=# select count(a.pubmedid) from omnicorp.CL a WHERE a.curie = 'CL:0000738'
;
 count  
 374262
(1 row)

robokop=# 
robokop=# select count(distinct a.pubmedid) from omnicorp.CL a WHERE a.curie = 'CL:0000738'
;
 count  
 305481
(1 row)
```

Going back to the omnicorp files, there don't seem to be dups, but the number of pubmeds for this CL is also only about 74000, so I'm not sure yet what's going on...

**Comment by cbizon** [comment]
So it looks like the files that I think we should have loaded don't contain papers that use the term "leucocyte", but only the ones that spell it "leukocyte" (very weak spot check).

@balhoff Did the latest run not incorporate synonyms, or did it skip a bunch of papers (the lowest pubmed in this run for CL:0000738 is something like 99000)

@YaphetKG did we load the files in /projects/sequence_analysis/vol3/embeddings/prep/omnicorp?

**Comment by kennethmorton** [comment]
So it seems like this should be fixed at the postgres level, but at the same time we need to update the manager API call to try to hit the redis cache. We will get on that.

**Comment by cbizon** [comment]
Looks like there was a problem with the omnicorp files which has now been fixed.  So we need to reload omnicorp + cache.
