### ISSUE TITLE
ROBOKOP KG password request?

### ISSUE THREAD

**Issue by karafecho** [NCATS-Gamma/robokop#447]
I was going to play around a bit while at the hackathon, but...

![image](https://user-images.githubusercontent.com/26254388/65002424-bcd6eb00-d8c1-11e9-9d6b-f90db5edee30.png)

I tried it again while at the hotel, and all is fine...

![image](https://user-images.githubusercontent.com/26254388/65002473-fa3b7880-d8c1-11e9-9918-39019033e72f.png)

I guess this has to do with the network issues that were noted today (and I couldn't hear from the back of the room)?

**Comment by kennethmorton** [comment]
This is due to ports being blocked on the wifi network. Not a robokop issue.
