### ISSUE TITLE
Ranking Issue for very basic question

### ISSUE THREAD

**Issue by kennethmorton** [NCATS-Gamma/robokop#448]
Why does this question fail to rank?

https://robokop.renci.org/q/4b4fb2d1-1577-418b-8626-114951482e32/

**Comment by patrickkwang** [comment]
Messenger's /score is timing out. Probably due to a bug. I'm looking into it.

**Comment by patrickkwang** [comment]
https://github.com/NCATS-Gamma/robokop-messenger/commit/4999e9e41236a04d4875f7af08c19330d8f95d57
