### ISSUE TITLE
fix gtex

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#455]
In our graph right now, I'm not sure gtex is right.   I'm not able to find variants that decrease expression of SLC16A11, along with the anatomical feature.  

Let's also add this query to the guide on robokopkg

Also, GTEX is not cached for some reason.

**Comment by PhillipsOwen** [comment]
i believe this has been resolved with the modifications that Yaphet and i did. I am not sure if Yaphet has posted his part of the code mods.

**Comment by cbizon** [comment]
We had a good GTEx query - can you find it and add it to the guide for robokopkg & deploy so it shows up?  @YaphetKG can you point Phil in the right direction and @EvanDietzMorris can you make sure Phil has the correct query?

**Comment by cbizon** [comment]
This is the query:
```
match (g:gene)-[e1:decreases_expression_of]-(s:sequence_variant)-[e2]-(a:anatomical_entity)--(g) where g.id='HGNC:23093' and any (q in e1.hyper_edge_id where any (w in e2.hyper_edge_id where w=q)) return *
```

**Comment by PhillipsOwen** [comment]
going to start to implement this now. i just had Yaphet drag me through what needs to be updated.

**Comment by PhillipsOwen** [comment]
should be all set. i added the query to the "nonlinear' list in queries.adoc.

changes were merged with master and deployed on robokopkg.renci.org
