### ISSUE TITLE
ranking ignoring support edges?

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#477]
https://robokop.renci.org/a/097cb001-7caa-4d21-9f46-9ddfaff28e6b_03d17ce3-0bf0-433f-ba50-d482726e66a2/

The query is (SVIL gene)-(variant)-(phenotpye)   (autism).  So there's no edge in the query from autism to other things.  But some phenotypes will have a support edge going to autism.

For instance, 'intelligence' shares 1100 publications with autism, but it gets the same score as emphesyma pattern measurement, which shares none.  And both get a lower score than some other things that also share none (but have an extra 'real' edge between the variant and gene).

But this 1100 publications should count for a lot? Or at least some?

**Comment by cbizon** [comment]
Here's another example

 https://robokop.renci.org/a/1f7c30db-6430-4b9b-92bb-346e2fdb7dfc_b02549c5-d100-42f7-84a9-0b1d37b17d08/

This is just brain -has_part-> cell

There are lots of counts, and it's possible that because of the normalization scores wouldn't be monotonic to the number of publications between the brain and the cell.  But the scores are all the same, which seems far less likely.

**Comment by patrickkwang** [comment]
This results from a bug in scoring with disconnected nodes, like autism in the above example. In https://github.com/NCATS-Gamma/robokop-messenger/commit/b759b28b346df4765d14d4898e48b1ede689853f this is corrected, and these answers are given a score of 0. This is perhaps undesirable, and is addressed by #481.
