### ISSUE TITLE
Allow access to Neo4j via HTTPS

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Gamma/robokop#482]
It is supposed to be available on port 7473, but I can't get it to work on robokopdb2.renci.org.

**Comment by YaphetKG** [comment]
Hey Patrick, I tried using 7474, and it worked out fine , atleast for GET http://robokopdb2.renci.org:7474/db/data/ ,

**Comment by YaphetKG** [comment]
Robokopdb2 is now open for https too.
