### ISSUE TITLE
Data files are needed to initialize omnicorp db

### ISSUE THREAD

**Issue by Prakash2403** [NCATS-Gamma/robokop#491]
Omnicorp DB is empty. I am not sure but ranking algorithm depends on it. I took a look at `create_omnicorp.sql` which seems to create relevant tables, but I am unable to find corresponding data files.

**Comment by Prakash2403** [comment]
@YaphetKG @patrickkwang Any updates on this?

**Comment by YaphetKG** [comment]
Hi @Prakash2403  sorry for the delay on, this we are on process of hosting those files on robokopkg.renci.org, will update you once those files are hosted over there.

**Comment by Prakash2403** [comment]
Okay, kindly notify once it is done. Thanks for the help

**Comment by YaphetKG** [comment]
Hi @Prakash2403, the dump files for Omnicorp and also the request cache (if you'd like to prepopulate your request cache with the service calls) are now hosted over at https://robokopkg.renci.org. Under the browse dump files section.

**Comment by Prakash2403** [comment]
HI @YaphetKG, Unable to access the website. Says `The site can't be reached`.

**Comment by YaphetKG** [comment]
https was not up due to misconfiguration. It is working now.

**Comment by Prakash2403** [comment]
Yep, it's accessible :)

Thanks for all help :)
