### ISSUE TITLE
Layered layout in total graph

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#507]
When a query is a linear path, then show the aggregate graph in a layout like this: 
![image](https://user-images.githubusercontent.com/10744350/78067292-7714d800-7364-11ea-86ba-32874eb56495.png)

Alex re-arranges them by hand to get an image like this, but I think that there is probably a layout in the graph library that does it for you.

**Comment by kennethmorton** [comment]
@maximusunc we have talked about including more graph layout options under a menu located where the pruning slider is. This appears to be a good first option.

**Comment by kennethmorton** [comment]
Implemented in 97f051f and deployed. See the hierarchical button under the graph layout menu. 

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/1233522/78699169-74b8fd80-78d1-11ea-9672-0aac30e36804.png">
