### ISSUE TITLE
Question Creation Workflow overhaul

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Gamma/robokop#51]
Fire initial answerset creation immediately after question creation
Redo question page UI a bit to understand the state of initial questions (dependent on task history)

* No answerset exists
  * Answerset in progress -> Show "in progress"
  * KG refresh in progress -> Show "refreshing"
  * Otherwise -> Recommend action
* An answerset exists
  * Answerset failed -> Suggestion refresh
  * Answerset good -> Show normal: denote if refresh and answerset creation are in progress and show and disable buttons appropriately

**Comment by kennethmorton** [comment]
This is mostly complete but has issues when initial questions fail. Adding bug tag to prioritize.

**Comment by kennethmorton** [comment]
Fixed as of 91f34884166501b3aadca84b5c119db69b47fafd
