### ISSUE TITLE
Query timing out

### ISSUE THREAD

**Issue by Shalsh23** [NCATS-Gamma/robokop#514]
For the query in the figure below, clicking on `Graph` option for the first result, the query times out without giving any resulting graph.

![image](https://user-images.githubusercontent.com/8756596/85075096-a11fae80-b18b-11ea-88ad-bcd6baa3f5b7.png)

**Comment by maximusunc** [comment]
Fixed in #515 
The issue was with set node edges coming back with no publications field. The UI now checks for the publications field when pruning set nodes.
