### ISSUE TITLE
Does not show the direction of arrows connecting node of type named_thing

### ISSUE THREAD

**Issue by Shalsh23** [NCATS-Gamma/robokop#517]
<img width="913" alt="Screen Shot 2020-06-24 at 12 16 11 PM" src="https://user-images.githubusercontent.com/8756596/85593019-aa3dcf00-b614-11ea-8bcc-1713ede4fa53.png">

Also, is there a way to say that the direction of the arrow does not matter, and results with arrows going both ways should be furnished?

**Comment by patrickkwang** [comment]
Regarding undirected edges, I believe that ROBOKOP ignores the edge direction IFF there is no predicate defined for the edge.

**Comment by patrickkwang** [comment]
Is the same true for displaying edges, @maximusunc?

**Comment by maximusunc** [comment]
In the UI, if an edge doesn't have a predicate, we don't show the arrows. If you were to add a predicate to one of the edges attached to the named_thing, it would then show a directed arrow. Like Patrick mentioned, the backend treats all non-predicated edges as bidirectional. Please reopen if that doesn't answer your questions!
