### ISSUE TITLE
Integrate new concept type modeling with UI

### ISSUE THREAD

**Issue by kennethmorton** [NCATS-Gamma/robokop#54]
Currently we use the old KG type model in the UI. This is all hard coded in JS, which is bad.

[Searching with biolink/monarch](https://owlsim.monarchinitiative.org/api/#!/search/get_search_entities) breaks for some types because our types don't match biolink.

We should:
- Deliver a list of available concept types from the server for the question editor. This allows it to be updatable.
- Determine a viable term search method for each concept type. biolink works well for disease and cell and may work for others. 
- Integrate these on the fly delivered new concept types into the UI

**Comment by patrickkwang** [comment]
This is largely done, but still needs to incorporate the biolink overlay stuff in a nice way.

**Comment by kennethmorton** [comment]
biological_process_or_molecular_function and other composite types still cause issues.

Adding bug to prioritize.

**Comment by kennethmorton** [comment]
After 91f34884166501b3aadca84b5c119db69b47fafd we have removed composite types from the UI and they have been mostly removed from the lower levels.
