### ISSUE TITLE
Screen for duplicate answersets

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Gamma/robokop#56]
We probably can't know if the answers will be different until we go look for them, but we should be able to identify whether they are the same afterward. If we get a duplicate, do the following:

1. Discard the older answerset.
2. Send the user a message saying that they made a duplicate and point them to the new answerset.

We will have essentially updated the timestamp on the duplicated answerset.

**Comment by kennethmorton** [comment]
What about old links? Discard the newer answers but updated the timestamp on the older. Or at least use the same id for the newer answers.

**Comment by patrickkwang** [comment]
All of the links to answersets are generated when we load the question page based on the answersets available, but it's true that if someone copied the permalink it could break. I agree, let's discard the new answerset and update the timestamp on the old one.

**Comment by patrickkwang** [comment]
Not a big problem. Reopen if there are performance slowdowns.
