### ISSUE TITLE
Cannot identify dump file or raw data location 

### ISSUE THREAD

**Issue by wrosko** [NCATS-Gamma/robokop#571]
HI there, I wish to recreate the robokop service but can't seem to identify where the data dump is located or where the underlying database exists.

Can someone help me?

**Comment by YaphetKG** [comment]
Hi @wrosko , We have a couple of different versions, 
- [Robokop + genetics( gwas gtex) 3-4-2021 Neo4j-3.5](https://stars.renci.org/var/robokop_neo4j_backups/baseline_plus_genetics_3_4_2021.dump) this is a version that works with neo4j 3.5 . This dataset has node types and edge types that have not yet been standardized to the latest [Biolink standard](https://biolink.github.io/biolink-model/)
- [Robokop-3-4-2021 + Cord19  Neo4j-3.5](https://stars.renci.org/var/robokop_neo4j_backups/baseline_plus_genetics_plus_cord_3_4_2021.dump) this contains more data coming from processing Cord19 papers using Scigraph. 
- [Robokop baseline 09-02-2021  Neo4j 4.2 ](https://stars.renci.org/var/plater/bl-2.1/Baseline_2.1.0_09022021.dump) Basline graph much smaller than the next two, doesn't contain gtex and gwas sets. 
- [Robokop + genetics  09-08-2021 Neo4j 4.2](https://stars.renci.org/var/plater/bl-2.1/genetics-09082021-neo4j-4.2.dump) using later version of robokop with some node id changes, and better relation ships
- [Robokop 09-08-2021+ Cord19  Neo4j 4.2 ](https://stars.renci.org/var/plater/bl-2.1/covid-09132021-neo4j-4.2.dump) with cord 19 set added.

**Comment by wrosko** [comment]
Thanks @YaphetKG I appreciate the response

Do you have a place in this live repo where you process raw data to the KG? Something similar to this: https://github.com/NCATS-Gamma/robokop-interfaces/blob/master/greent/greent-api.conf
