### ISSUE TITLE
bionames exact

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#65]
When one calls bionames, you can get a bunch of results back: 
```
curl -X GET --header 'Accept: application/json' 'https://bionames.renci.org/lookup/Acne%20Vulgaris/disease/'
```
will return

```
[
  {
    "id": "MONDO:0011438",
    "label": "acne (disease)"
  },
  {
    "id": "SNOMED:88616000",
    "label": "Acne vulgaris"
  },
  {
    "id": "MONDO:0011438",
    "label": "acne (disease)"
  },
  {
    "id": "MONDO:0006521",
    "label": "acneiform dermatitis"
  },
  {
    "id": "MONDO:0024304",
    "label": "ichthyosis vulgaris"
  },
...
]
```

2 points:

1. MONDO:0011438 is returning twice

2. Some of these matches are better than others.   0011438 has an exact synonym that is the search term (Acne Vulgaris) but MONDO:0024304 does not.  The first is a better match in a definable way.  It would be great if the output somehow indicated this.

**Comment by stevencox** [comment]
The dups and some of the chaotic results seem to have sprung from including calls to owlsim. The mondo base type of ebola is also returned when one searches owlsim on ebola. I've removed owlsim from disease search and redeployed.
