### ISSUE TITLE
Bionames - Alkaptonuria is an anatomical_entity?

### ISSUE THREAD

**Issue by kennethmorton** [NCATS-Gamma/robokop#67]
These both return some results, while I think only the second should:

`curl -X GET --header 'Accept: application/json' 'https://bionames.renci.org/lookup/alkaptonuria/anatomical_entity/'`

`curl -X GET --header 'Accept: application/json' 'https://bionames.renci.org/lookup/alkaptonuria/disease/'`

**Comment by patrickkwang** [comment]
For anything other than a drug, the bionames lookup is searching Onto, which doesn't even accept a concept type. So many results are essentially not filtered by concept.

**Comment by stevencox** [comment]
Empty set returned after redeploy.
