### ISSUE TITLE
change type of nodes in knowledge map

### ISSUE THREAD

**Issue by cbizon** [NCATS-Gamma/robokop#70]
Currently our concept nodes in neo4j also have a label for what they are the concept of.  So, for example, we have a concept node for "gene" which has label "concept" but also label "gene" and also name "gene".  We should take the label "gene" off, as the node is not a gene, it's the concept of a gene.  Also, it gets weird in terms of pulling results (or at least browsing neo4j).

**Comment by patrickkwang** [comment]
Ditto for Type nodes?

**Comment by cbizon** [comment]
Yeah, I'm not sure we even need the type nodes any more.

**Comment by cbizon** [comment]
So I think that there are a few things to do here:
1) modify the type-graph creation code to not add Type nodes
2) modify the type-graph code to not add e.g. "gene" as a label to the concept nodes
3) Make both changes by hand to the live databases at robokopdb2 and robokopkg

**Comment by YaphetKG** [comment]
Cleared the labels from concept nodes, additionally index was created for all concept nodes, and unique ID constraint is applied on named_thing (as this is the base class for every node types). Graph initialization steps have been changed accordingly.
