### ISSUE TITLE
Answers have weird names sometimes

### ISSUE THREAD

**Issue by kennethmorton** [NCATS-Gamma/robokop#75]
I dont think literature-co-occurence should appear in the answer name, sometimes it does.

**Comment by kennethmorton** [comment]
What is a good way to label answers that don't get crazy long?

The impetus for this bug has been solved. Leaving open and switching to enhancement so that we remember to make better names one day.

**Comment by patrickkwang** [comment]
Answers do not have names any more. The answerset browser allows people to get the gist of things quickly, so I don't feel the need to have short text summaries.
