### ISSUE TITLE
suggestion from Melissa Haendel: document licensing of KSs used

### ISSUE THREAD

**Issue by saramsey** [NCATS-Gamma/robokop#76]
For the reasoners- you may wish to examine licensing as a criteria for inclusion. You can request license evaluation if you are uncertain here:
http://reusabledata.org/
https://github.com/reusabledata/reusabledata/issues/new
GitHub
Build software better, together
GitHub is where people build software. More than 27 million people use GitHub to discover, fork, and contribute to over 80 million projects.
or you can also curate your own and make a PR. I would greatly appreciate if we can ensure that all Translator Knowledge sources are curated for licensing information and we would be grateful for assistance.

**Comment by YaphetKG** [comment]
Here is a list of licenses I have gathered from our services, annotators and crawlers. https://docs.google.com/document/d/1RDK9AntxD1yzqS67U4OGUzoUHx6963oKAtW8B-kqEvw/edit?usp=sharing

**Comment by cbizon** [comment]
robokop-interfaces now includes a yaml file that lists each source, the license that source employs, the url where you can read the statement that this is the license for that source, and a url that gives the citation for the source.   This yaml file gets smushed into a section of the robokopkg guide.  We should probably include a form of it somewhere on robokop as well.  Once that is done, we can close this issue.

**Comment by maximusunc** [comment]
The UI now gets that yaml file from interfaces and displays it on the About page.
