### ISSUE TITLE
New Machine Questions - Editor and corresponding enhancements to Ranker (and possibly Builder)

### ISSUE THREAD

**Issue by kennethmorton** [NCATS-Gamma/robokop#80]
AKA "Branching Questions"

Output is a graph template. Nodes have optional type and id properties. Edges have optional min-length, max-length, and predicate properties.

OR: can be encoded by lists of types/ids/predicates.
Sets (perhaps a bad name). 

Must be able to re-populate (fork).

Full specification coming soon.

**Comment by cbizon** [comment]
We probably need to chop this issue up into smaller pieces to assign people to.
