### ISSUE TITLE
Duplicate Edges? or Two Directional Edges?

### ISSUE THREAD

**Issue by kennethmorton** [NCATS-Gamma/robokop#86]
[An  example](http://robokop.renci.org/a/4lw4spOIxrso_1471/1424)

It seems to come from having multiple builds and services connecting in both directions. Not sure if this is really a Builder or Ranker issue.

**Comment by cbizon** [comment]
One of these is pointing the wrong way - I think that I fixed this in going through more edge standardization stuff, but I'll leave the ticket open until convinced.

**Comment by cbizon** [comment]
Need to test to see if this is still going on.

**Comment by cbizon** [comment]
This is apparently fixed.  There are still multiple edges connecting two nodes but this is either because they have different predicates from one service or the same predicate from two different services.
