### ISSUE TITLE
Unsorted Ranking

### ISSUE THREAD

**Issue by kennethmorton** [NCATS-Gamma/robokop#97]
Not sure how this happens but once in a blue moon it does. 

[An Example](  http://robokop.renci.org/a/QM1TOgeOQBg3_1462)

**Comment by patrickkwang** [comment]
I think this comes from how we store and retrieve the answers in SQLAlchemy. We can define a default sorting on retrieval, but we'll have to expose the proper rank as a float property, i.e. not buried somewhere inside a 'score' dict. Our score dict already has two fields again: rank_score and pre_score. I propose that we make the rank_score a 1st-class property, and stash any other data we might want to save in some kind of 'misc' property, which will be a dict.

**Comment by patrickkwang** [comment]
d7210ee42acace86fa668f77e2620ce54d5adb98
